#!/bin/bash

./cache_simulator ./traces/008.espresso.din -m -a 2
./cache_simulator ./traces/013.spice2g6.din -m -a 2
./cache_simulator ./traces/015.doduc.din -m -a 2 
./cache_simulator ./traces/022.li.din -m -a 2
./cache_simulator ./traces/023.eqntott.din -m -a 2
./cache_simulator ./traces/026.compress.din -m -a 2
./cache_simulator ./traces/034.mdljdp2.din -m -a 2
./cache_simulator ./traces/039.wave5.din -m -a 2
./cache_simulator ./traces/047.tomcatv.din -m -a 2
./cache_simulator ./traces/048.ora.din -m -a 2
./cache_simulator ./traces/085.gcc.din -m -a 2
./cache_simulator ./traces/089.su2cor.din -m -a 2
./cache_simulator ./traces/090.hydro2.din -m -a 2
./cache_simulator ./traces/093.nasa7.din -m -a 2
./cache_simulator ./traces/094.fpppp.din -m -a 2

./cache_simulator ./traces/008.espresso.din -m -a 4
./cache_simulator ./traces/013.spice2g6.din -m -a 4
./cache_simulator ./traces/015.doduc.din -m -a 4
./cache_simulator ./traces/022.li.din -m -a 4
./cache_simulator ./traces/023.eqntott.din -m -a 4
./cache_simulator ./traces/026.compress.din -m -a 4
./cache_simulator ./traces/034.mdljdp2.din -m -a 4
./cache_simulator ./traces/039.wave5.din -m -a 4
./cache_simulator ./traces/047.tomcatv.din -m -a 4
./cache_simulator ./traces/048.ora.din -m -a 4
./cache_simulator ./traces/085.gcc.din -m -a 4
./cache_simulator ./traces/089.su2cor.din -m -a 4
./cache_simulator ./traces/090.hydro2.din -m -a 4
./cache_simulator ./traces/093.nasa7.din -m -a 4
./cache_simulator ./traces/094.fpppp.din -m -a 4

./cache_simulator ./traces/008.espresso.din -m -a 8
./cache_simulator ./traces/013.spice2g6.din -m -a 8
./cache_simulator ./traces/015.doduc.din -m -a 8
./cache_simulator ./traces/022.li.din -m -a 8
./cache_simulator ./traces/023.eqntott.din -m -a 8
./cache_simulator ./traces/026.compress.din -m -a 8
./cache_simulator ./traces/034.mdljdp2.din -m -a 8
./cache_simulator ./traces/039.wave5.din -m -a 8
./cache_simulator ./traces/047.tomcatv.din -m -a 8
./cache_simulator ./traces/048.ora.din -m -a 8
./cache_simulator ./traces/085.gcc.din -m -a 8
./cache_simulator ./traces/089.su2cor.din -m -a 8
./cache_simulator ./traces/090.hydro2.din -m -a 8
./cache_simulator ./traces/093.nasa7.din -m -a 8
./cache_simulator ./traces/094.fpppp.din -m -a 8